name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Create local.properties
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: echo maps_api_key="$MAPS_API_KEY" > ./local.properties
      - name: Read local.properties
        id: props
        uses: juliangruber/read-file-action@v1
        with:
          path: ./local.properties
      - name: Echo local.properties
        run: echo ${{ steps.props.outputs.content }}
      - name: Gradle Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
